### ISSUE TITLE
Problem with Nginx and IPv6

### ISSUE THREAD

**Issue by gnilebein** [virtualmin/virtualmin-nginx-ssl#1]
Hello,

i have a server with IPV6 enabled. But if i activate SSL for that server, ssl is only active for IPv4. There is no entry for IPv6 in Nginx Config.

My Setup: Ubuntu 14.04 Nginx 1.11.7 Virtualmin 5.05 GPL

Is this issue caused by myself or is this an general issue?

The Second thing is, that virtualmin always adds "ipv6only=on" to the listen configuratoin in nginx. But this causes an error while restarting nginx:

nginx: [emerg] duplicate listen options for....

Beste regards, Patrick

**Comment by jcameron** [comment]
This is a known bug, which will be fixed when we release the next version of the Nginx SSL plugin for Virtualmin.

**Comment by gnilebein** [comment]
Thanks:)
